//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attributes_to_attributes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attributes::Entity",
        from = "Column::ParentId",
        to = "super::attributes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Attributes2,
    #[sea_orm(
        belongs_to = "super::attributes::Entity",
        from = "Column::AttributeId",
        to = "super::attributes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Attributes1,
}

impl ActiveModelBehavior for ActiveModel {}
