//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub desc: String,
    pub cost: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::attributes::Entity> for Entity {
    fn to() -> RelationDef {
        super::cards_to_attributes::Relation::Attributes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cards_to_attributes::Relation::Cards.def().rev())
    }
}

impl Related<super::decks::Entity> for Entity {
    fn to() -> RelationDef {
        super::decks_to_cards::Relation::Decks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::decks_to_cards::Relation::Cards.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
