//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::cards_to_attributes;

use super::{attributes, cards};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cards_to_attributes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub card_id: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_id: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attributes::Entity",
        from = "Column::AttributeId",
        to = "super::attributes::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Attributes,
    #[sea_orm(
        belongs_to = "super::cards::Entity",
        from = "Column::CardId",
        to = "super::cards::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Cards,
}

impl Related<super::attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attributes.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

pub struct CardsToAttributes;

impl Linked for CardsToAttributes {
    type FromEntity = cards::Entity;
    type ToEntity = attributes::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            cards_to_attributes::Relation::Cards.def().rev(),
            cards_to_attributes::Relation::Attributes.def(),
        ]
    }
}

impl ActiveModelBehavior for ActiveModel {}
