//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cardsets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cardsets_to_cards::Entity")]
    CardsetsToCards,
}

impl Related<super::cardsets_to_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardsetsToCards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
