//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "EntityToEntities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub relation_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::ChildId",
        to = "super::entities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Entities2,
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::ParentId",
        to = "super::entities::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Entities1,
}

impl ActiveModelBehavior for ActiveModel {}
