//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "EntityToProperties")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub entity_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub property_name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::EntityId",
        to = "super::entities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Entities,
}

impl Related<super::entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
