//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Entities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub desc: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::entity_to_properties::Entity")]
    EntityToProperties,
}

impl Related<super::entity_to_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityToProperties.def()
    }
}

impl Related<super::attributes::Entity> for Entity {
    fn to() -> RelationDef {
        super::entity_to_attributes::Relation::Attributes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::entity_to_attributes::Relation::Entities.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
