//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod attributes;
pub mod entities;
pub mod entity_to_attributes;
pub mod entity_to_entities;
pub mod entity_to_properties;
